plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.tapreplay'
    compileSdk 35

    defaultConfig {
        applicationId 'com.cyh312.douyinfilter'
        minSdk 28
        targetSdk 35
        versionCode 14
        versionName '0.7.6-internal.2'
        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    androidResources {
        noCompress += ['onnx']
    }

    packaging {
        jniLibs {
            useLegacyPackaging = false
        }
        resources {
            excludes += ['META-INF/LICENSE*', 'META-INF/NOTICE*']
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.29.0'
}
