package com.example.tapreplay;

import android.content.Context;
import android.media.AudioAttributes;
import android.media.AudioFormat;
import android.media.AudioPlaybackCaptureConfiguration;
import android.media.AudioRecord;
import android.media.MediaRecorder;
import android.media.projection.MediaProjection;
import android.media.projection.MediaProjectionManager;
import android.os.Build;

import java.util.ArrayList;

/**
 * Captures internal playback audio on Android 10+ through MediaProjection.
 * This is not microphone recording. It analyzes the audio stream generated by the game/app itself,
 * when the game and system policy allow playback capture.
 */
public final class InternalAudioRecorder {
    public interface Listener {
        void onState(String text);
    }

    private final Context context;
    private final Listener listener;
    private final Object lock = new Object();

    private AudioRecord audioRecord;
    private MediaProjection mediaProjection;
    private Thread worker;
    private volatile boolean recording = false;
    private final ArrayList<short[]> chunks = new ArrayList<>();
    private int totalSamples = 0;
    private String lastError = "";

    public InternalAudioRecorder(Context context, Listener listener) {
        this.context = context.getApplicationContext();
        this.listener = listener;
    }

    public boolean isRecording() {
        return recording;
    }

    public String getLastError() {
        return lastError;
    }

    public boolean start() {
        if (recording) return true;
        lastError = "";
        if (Build.VERSION.SDK_INT < 29) {
            lastError = "内部音频捕获需要 Android 10+";
            emit(lastError);
            return false;
        }
        if (!AudioCaptureHolder.hasProjectionGrant()) {
            lastError = "请先回到 TapReplay 主界面授权内部音频捕获";
            emit(lastError);
            return false;
        }

        try {
            MediaProjectionManager manager = (MediaProjectionManager) context.getSystemService(Context.MEDIA_PROJECTION_SERVICE);
            mediaProjection = AudioCaptureHolder.createProjection(manager);
            if (mediaProjection == null) {
                lastError = "内部音频授权无效，请重新授权";
                emit(lastError);
                return false;
            }

            AudioPlaybackCaptureConfiguration config = new AudioPlaybackCaptureConfiguration.Builder(mediaProjection)
                    .addMatchingUsage(AudioAttributes.USAGE_GAME)
                    .addMatchingUsage(AudioAttributes.USAGE_MEDIA)
                    .addMatchingUsage(AudioAttributes.USAGE_UNKNOWN)
                    .build();

            AudioFormat format = new AudioFormat.Builder()
                    .setSampleRate(AudioJumpAnalyzer.SAMPLE_RATE)
                    .setEncoding(AudioFormat.ENCODING_PCM_16BIT)
                    .setChannelMask(AudioFormat.CHANNEL_IN_MONO)
                    .build();

            int minBuffer = AudioRecord.getMinBufferSize(
                    AudioJumpAnalyzer.SAMPLE_RATE,
                    AudioFormat.CHANNEL_IN_MONO,
                    AudioFormat.ENCODING_PCM_16BIT);
            if (minBuffer <= 0) minBuffer = AudioJumpAnalyzer.SAMPLE_RATE;
            int bufferSize = Math.max(minBuffer * 2, AudioJumpAnalyzer.SAMPLE_RATE / 2);

            audioRecord = new AudioRecord.Builder()
                    .setAudioFormat(format)
                    .setBufferSizeInBytes(bufferSize)
                    .setAudioPlaybackCaptureConfig(config)
                    .build();

            if (audioRecord.getState() != AudioRecord.STATE_INITIALIZED) {
                lastError = "内部音频录制器初始化失败";
                cleanup();
                emit(lastError);
                return false;
            }

            synchronized (lock) {
                chunks.clear();
                totalSamples = 0;
            }
            recording = true;
            audioRecord.startRecording();
            worker = new Thread(this::readLoop, "TapReplayInternalAudioRecorder");
            worker.start();
            emit("内部音频分析中...");
            return true;
        } catch (SecurityException se) {
            lastError = "缺少录音/内部音频权限，请在系统权限中允许 TapReplay 录音";
            recording = false;
            cleanup();
            emit(lastError);
            return false;
        } catch (Exception e) {
            lastError = "内部音频启动失败：" + e.getClass().getSimpleName();
            recording = false;
            cleanup();
            emit(lastError);
            return false;
        }
    }

    public short[] stopAndGetPcm() {
        if (!recording && audioRecord == null) return mergeChunks();
        recording = false;
        try {
            if (worker != null) worker.join(800);
        } catch (InterruptedException ignored) { }
        cleanup();
        short[] pcm = mergeChunks();
        emit("内部音频已结束，样本 " + pcm.length);
        return pcm;
    }

    public void discard() {
        recording = false;
        try {
            if (worker != null) worker.join(300);
        } catch (InterruptedException ignored) { }
        cleanup();
        synchronized (lock) {
            chunks.clear();
            totalSamples = 0;
        }
    }

    private void readLoop() {
        short[] buffer = new short[4096];
        while (recording && audioRecord != null) {
            int read = audioRecord.read(buffer, 0, buffer.length);
            if (read > 0) {
                short[] copy = new short[read];
                System.arraycopy(buffer, 0, copy, 0, read);
                synchronized (lock) {
                    chunks.add(copy);
                    totalSamples += read;
                }
            }
        }
    }

    private short[] mergeChunks() {
        synchronized (lock) {
            short[] pcm = new short[totalSamples];
            int offset = 0;
            for (short[] chunk : chunks) {
                System.arraycopy(chunk, 0, pcm, offset, chunk.length);
                offset += chunk.length;
            }
            return pcm;
        }
    }

    private void cleanup() {
        try {
            if (audioRecord != null) {
                if (audioRecord.getRecordingState() == AudioRecord.RECORDSTATE_RECORDING) {
                    audioRecord.stop();
                }
                audioRecord.release();
            }
        } catch (Exception ignored) { }
        audioRecord = null;

        try {
            if (mediaProjection != null) mediaProjection.stop();
        } catch (Exception ignored) { }
        mediaProjection = null;
        worker = null;
    }

    private void emit(String text) {
        if (listener != null) listener.onState(text);
    }
}
